server:
  port: 8222
spring:
  datasource:
    username: root
    password: Kavita@507
    url: jdbc:mysql://localhost:3306/orders_db

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format-sql: true